In [1]:
import numpy as np
import pandas as pd

In [80]:
df = pd.read_csv('results/results_100_10000.csv', header=None)
results = df.to_numpy()
X=results[:100,:-1]
y=(results[:100,-1]-0.5)*10

In [81]:
x_unique = np.unique(X)
num_units = (len(x_unique)-1)//2
costs = np.zeros(num_units+1)
print(costs)

[0. 0. 0. 0. 0.]


In [82]:
(keys, values) = np.unique(X[0], return_counts=True)
neg_index = np.nonzero(keys<0)
neg_cost = np.sum(costs[np.abs(keys[neg_index]).astype(int)]*values[neg_index])
pos_index = np.nonzero(keys>0)
pos_cost = np.sum(costs[np.abs(keys[pos_index]).astype(int)]*values[pos_index])
delta_cost = pos_cost-neg_cost

In [83]:
def MSE(X, y, costs):
    total_error = 0
    for row in range(X.shape[0]):
        (keys, values) = np.unique(X[row], return_counts=True)
        neg_index = np.nonzero(keys<0)
        neg_cost = np.sum(costs[np.abs(keys[neg_index]).astype(int)]*values[neg_index])
        pos_index = np.nonzero(keys>0)
        pos_cost = np.sum(costs[np.abs(keys[pos_index]).astype(int)]*values[pos_index])
        delta_cost = pos_cost-neg_cost
        total_error += (y[row]-delta_cost)**2
        # if row%1000 == 0:
        #     print(row)
    return total_error/X.shape[0]

In [84]:
print(MSE(X, y, costs))

12.010399999999997


In [99]:
# def perturb(costs, rate=1, min_change=0.1):
#     return np.maximum(0,costs+((np.random.randn(len(costs))-0.2)*rate))

In [103]:
# costs = np.zeros((len(x_unique)-1)//2+1)
# min_error = 99999
# min_costs = costs
# epochs = 10
# for generation in range(10000):
#     costs = np.random.randn(len(min_costs))*10
#     old_error = MSE(X,y,costs)
#     for epoch in range(epochs):
#         new_costs = perturb(costs,rate=1-epoch/epochs)
#         new_error = MSE(X,y,new_costs)
#         if new_error < old_error:
#             old_error = new_error
#             costs = new_costs
#             # print(generation, epoch, old_error)
#         if epoch%10==0:
#             print(generation, epoch, old_error)
#     if old_error < min_error:
#         min_error = old_error
#         min_costs = np.copy(costs)
#     print(min_costs, min_error)



0 0 8105.8285696332
[ 4.1998348   0.03646112  0.1181709  22.8169117  21.5607239 ] 6943.456502579168
1 0 278.16285306343804
[0.         0.         0.98926005 5.27298123 0.        ] 243.29397410093898
2 0 1359.8634751039656
[0.         0.         0.98926005 5.27298123 0.        ] 243.29397410093898
3 0 248.84429245409433
[2.23701125 2.80336156 0.8485116  0.04397706 0.14715395] 101.47553325262385
4 0 4037.1416941042526
[2.23701125 2.80336156 0.8485116  0.04397706 0.14715395] 101.47553325262385
5 0 502.41623149089736
[0.28999664 2.47458341 0.98462739 0.23431429 0.        ] 91.70206647750439
6 0 1241.7204738094574
[0.28999664 2.47458341 0.98462739 0.23431429 0.        ] 91.70206647750439
7 0 434.05644537352987
[0.28999664 2.47458341 0.98462739 0.23431429 0.        ] 91.70206647750439
8 0 3622.2888884412846
[0.28999664 2.47458341 0.98462739 0.23431429 0.        ] 91.70206647750439
9 0 1688.4024629050111
[0.28999664 2.47458341 0.98462739 0.23431429 0.        ] 91.70206647750439
10 0 3972.0794

KeyboardInterrupt: 

In [ ]:
test = np.array([[1,2,1,2,0],[1,2,0,1,1]])
print(np.unique(test, return_counts=True, axis=1))

(array([[0, 1, 1, 2, 2],
       [1, 0, 1, 1, 2]]), array([1, 1, 1, 1, 1], dtype=int64))
